### ISSUE TITLE
crosspoints.py error  ValueError: math domain error

### ISSUE THREAD

**Issue by uditabasu** [solgenomics/snpbinner#6]
Hi,
I was trying to use snpbinner crosspoints command with my SNP dataset. However, I am getting this following error :

Traceback (most recent call last):
  File "/home/rama/.local/bin/snpbinner", line 9, in <module>
    load_entry_point('snpbinner==0.2.3', 'console_scripts', 'snpbinner')()
  File "/home/rama/Downloads/softwares/SNPbinner-master/snpbinner/__main__.py", line 24, in main
    program_run_dict[program_to_run](**arg_dict_to_pass)
  File "/home/rama/Downloads/softwares/SNPbinner-master/snpbinner/crosspoints.py", line 9, in _crosspoints_batcher
    crosspoints(input_path[0],output_path,predicted_homogeneity,predicted_cross_count,chrom_len,min_state_length,min_state_ratio)
  File "/home/rama/Downloads/softwares/SNPbinner-master/snpbinner/crosspoints.py", line 86, in crosspoints
    hmm_all          = hmm_all)
  File "/home/rama/Downloads/softwares/SNPbinner-master/snpbinner/crosspoints.py", line 94, in _find_crosspoints
    cross_points  = hmm_all.gapped_viterbi(snplist)
  File "/home/rama/Downloads/softwares/SNPbinner-master/snpbinner/crosspoints.py", line 276, in gapped_viterbi
    gap_transition_adjustment = log(gap_size)
ValueError: math domain error

When I am trying the same command with individual chromosome SNPs the command is working fine. I am a biologist, new to python. Please help me understand the problem.

Udita

**Comment by itaygonda** [comment]
SNPbinner is designed to work with individual chromosomes. I believe @dauglyon tried to do something more robust.
Any idea David?

**Comment by dauglyon** [comment]
@uditabasu Looks like gap_size is outside of the domain of the log function. You may have two SNPs annotated at the same chromosome position (which would make the gap between them zero) or incorrectly ordered (which might make the gap negative)

**Comment by uditabasu** [comment]
Thank you @dauglyon and @itaygonda . I figured out the problem. I was trying to work with all the chromosomes at a time. As @itaygonda mentioned I am supposed to work with single chromosome at a time.
